# This workflow will do a clean install of node dependencies, build the source code and run coverage analysis to upload to Codacy
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.ts'

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: canary
    - run: bun test --coverage --coverage-reporter=lcov
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage/lcov.info
    
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
